[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[redirects]]
  from = "/docs/*"
  to = "https://lookup-guides.netlify.app/:splat"
  status = 200
  force = false
